### ISSUE TITLE
Rename project?

### ISSUE THREAD

**Issue by jjeising** [voc/aes67-recorder#1]
Isn't this project suitable for all AES67 recording requirements? For more general applications a segment length of 30 or 60 minutes might be more appropriate, but as all this is configurable I don't see any reason this would not work as a general purpose AES67 audio recorder.

With AES67 compatibility enabled via Dante Controller this should also work in all Dante environments as recorder.

**Comment by MaZderMind** [comment]
@jjeising I thought about that for a while and when I think about what behavior I'd expect from a generic AES67 recorder, I'd not expect it to segmentize my recording.

**Comment by MaZderMind** [comment]
jup, renamed.
